[package]
name = "auxide-io"
version = "0.1.0"
edition = "2021"

[dependencies]
auxide = { version = "0.1.2", path = "../auxide" }
cpal = "0.15"
anyhow = "1.0"

[features]
jack = ["cpal/jack"]

[[example]]
name = "play_tone"
path = "examples/play_tone.rs"

[[example]]
name = "play_sine"
path = "examples/play_sine.rs"

[profile.release]
panic = "abort"
